[project]
name = "agent-handson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agent-framework>=1.0.0b251104",
    "azure-identity>=1.25.1",
    "python-dotenv>=1.2.1",
]
